# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Develop
tagline:          'A Jekyll theme'
description:      '웹디자이너였던 내가<br/>3달 뒤 <a>Back-End 개발자?</a>'
url:              https://ju-ei8ht.github.io/
baseurl:          ""

author:
  name:           '주8'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ju-ei8ht
